---
Name: silverstripe-icons
---
SiteConfig:
  extensions:
    - Icon_SiteConfigExtension

LeftAndMain:
  extra_requirements_css:
    - silverstripe-icons/fonts/font-awesome-4.3.0/css/font-awesome.min.css
    - silverstripe-icons/css/cms/min.css

ContentController:
  extensions:
    - Icon_ContentControllerExtension